a. Using Numpy, write a basic array of operations on single array to add x to each element of array and subtract y from each element of array. 

In [4]:
import numpy as np
x=np.arange(10)
print(x)
print(x+10)
print(x-10)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


b.Using Numpy, write a program to add, subtract and multiply two matrices. 

In [9]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(10,19).reshape(3,3)
print(x)
print(y)
print("The addition of x and y gives:\n",np.add(x,y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
The addition of x and y gives:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]


c. Write a Python program to do the following operations: Library: NumPy
i)	Create multi-dimensional arrays and find its shape and dimension 


In [20]:
n=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
k=np.array([[1,2,3],[3,4,5]])
print(k.ndim)
print(n.ndim)

2
3


ii)Create a matrix full of zeros and ones 

In [33]:
n=np.matrix(np.ones((3,2)))
print(n.ndim)


2


iii)	Reshape and flatten data in the array 

In [35]:
print(n.reshape(2,3))
print(n)
print(n.flatten())

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1. 1. 1. 1.]]


iv)	Append data vertically and horizontally 

In [44]:
n=np.arange(1,10).reshape(3,3)
print(n)
y=np.ones((1,3))
print(y)
print("Row concatenate: \n",np.concatenate((n,y),axis=0))
y=np.ones((3,1))
print("Col concatenate: \n",np.concatenate((n,y),axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]]
Row concatenate: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [1. 1. 1.]]
Col concatenate: 
 [[1. 2. 3. 1.]
 [4. 5. 6. 1.]
 [7. 8. 9. 1.]]


v)	Apply indexing and slicing on array 

In [53]:
n=np.arange(1,10).reshape(3,3)
print(n)
print("the slicing is:")
print(n[:2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
the slicing is:
[[1 2 3]
 [4 5 6]]


vi)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 

In [59]:
n=np.arange(1,10).reshape(3,3)
print(n)
print(np.min(n))
print(np.max(n))
print(np.mean(n))
print(np.std(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
5.0
2.581988897471611


vii)	Dot and matrix product of two arrays 

In [66]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(10,19).reshape(3,3)
print(x)
print(y)
print("the product of matric is :\n",np.dot(x,y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
the product of matric is :
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


viii)	Compute the Eigen values of a matrix 

In [69]:
print(np.linalg.eigvals(x))

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]


ix)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 

x)	Compute the multiplicative inverse of a matrix 

In [70]:
print(np.linalg.inv(x))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


xi)	Compute the rank of a matrix 

In [71]:
print(np.linalg.matrix_rank(x))

2


Compute the determinant of an array

In [72]:
print(np.linalg.det(x))

-9.51619735392994e-16
